-- ===================== FINAL NORMALIZED DDL.sql =====================

-- Drop and recreate the database
CREATE DATABASE medi_master;
USE medi_master;

-- ===================== PATIENT TABLE =====================
CREATE TABLE PATIENT (
    PID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    BLOOD_GROUP VARCHAR(5),
    AGE INT NOT NULL,
    ALLERGIES VARCHAR(255)
);

-- ===================== CHECKUP TABLE =====================
CREATE TABLE CHECKUP (
    CHECKUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    PID INT NOT NULL,
    DATE DATE NOT NULL,
    FOREIGN KEY (PID) REFERENCES PATIENT(PID)
);

-- ===================== AILMENT_DETAILS TABLE =====================
CREATE TABLE AILMENT_DETAILS (
    AID INT AUTO_INCREMENT PRIMARY KEY,
    CHECKUP_ID INT NOT NULL,
    AILMENT VARCHAR(100) NOT NULL,
    SEVERITY VARCHAR(50),
    FOREIGN KEY (CHECKUP_ID) REFERENCES CHECKUP(CHECKUP_ID)
);

-- ===================== MEDICINE TABLE =====================
CREATE TABLE MEDICINE (
    MNAME VARCHAR(100) PRIMARY KEY,
    TYPE VARCHAR(50),
    PRE_REQ TEXT,
    NEED TEXT,
    ALTERNATIVE_MNAME VARCHAR(100)
);

-- ===================== PRESCRIPTION_DETAILS TABLE =====================
CREATE TABLE PRESCRIPTION_DETAILS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CHECKUP_ID INT NOT NULL,
    MNAME VARCHAR(100) NOT NULL,
    REASON TEXT,
    DAYS INT NOT NULL,
    WORKING TEXT,
    FOREIGN KEY (CHECKUP_ID) REFERENCES CHECKUP(CHECKUP_ID),
    FOREIGN KEY (MNAME) REFERENCES MEDICINE(MNAME)
);

-- ===================== SYMPTOM TABLE =====================
CREATE TABLE SYMPTOM (
    SID INT PRIMARY KEY,
    Symptom VARCHAR(500),
    Category VARCHAR(100)
);

-- ===================== SYMPTOMS_USED TABLE =====================
CREATE TABLE SYMPTOMS_USED (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CHECKUP_ID INT NOT NULL,
    SID INT NOT NULL,
    FOREIGN KEY (CHECKUP_ID) REFERENCES CHECKUP(CHECKUP_ID),
    FOREIGN KEY (SID) REFERENCES SYMPTOM(SID)
);

-- ===================== SYMPTOM_MEDICINE_MAP TABLE =====================
CREATE TABLE SYMPTOM_MEDICINE_MAP (
    MAP_ID INT AUTO_INCREMENT PRIMARY KEY,
    Symptom VARCHAR(160) NOT NULL,
    MNAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (MNAME) REFERENCES MEDICINE(MNAME)
);

-- ===================== SIDE_EFFECTS TABLE (NORMALIZED) =====================
CREATE TABLE SIDE_EFFECTS (
    SIDE_EFFECT_ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

-- ===================== SIDE_EFFECT_MEDICINE_MAP TABLE =====================
CREATE TABLE SIDE_EFFECT_MEDICINE_MAP (
    MAP_ID INT AUTO_INCREMENT PRIMARY KEY,
    SIDE_EFFECT_ID INT NOT NULL,
    MNAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (SIDE_EFFECT_ID) REFERENCES SIDE_EFFECTS(SIDE_EFFECT_ID),
    FOREIGN KEY (MNAME) REFERENCES MEDICINE(MNAME)
);

-- ===================== TRIGGER TEST TABLES =====================
CREATE TABLE TEST_TRIGGER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    val VARCHAR(255)
);

CREATE TABLE trigger_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER //

CREATE TRIGGER trg_after_insert_test
AFTER INSERT ON TEST_TRIGGER
FOR EACH ROW
BEGIN
    INSERT INTO trigger_log (message)
    VALUES (CONCAT('Inserted value: ', NEW.val));
END;
//

-- ===================== STORED PROCEDURE TEST =====================
DELIMITER $$

CREATE PROCEDURE page_access_procedure(IN page_name VARCHAR(100), OUT message VARCHAR(255))
BEGIN
    SET message = CONCAT('Procedure Triggered: ', page_name, ' was accessed.');
END $$

DELIMITER ;


DELIMITER $$

CREATE FUNCTION page_access_function(page_name VARCHAR(100))
RETURNS VARCHAR(255)
DETERMINISTIC
BEGIN
    RETURN CONCAT('Function Triggered: ', page_name, ' was accessed.');
END $$

DELIMITER ;

